MD "%PROGRAMFILES%\SIGNAL RECOVERY\USBDriversV3"
XCOPY C:\SRTempFolder\*.* "%PROGRAMFILES%\SIGNAL RECOVERY\USBDriversV3" /s /Y
DEL "%PROGRAMFILES%\SIGNAL RECOVERY\USBDriversV3\xfer.bat"
RD C:\SRTempFolder