"""
This script is meant for developers. Run it FROM the command line using:

```
 python -m pymodaq_gui.resources.check_icons_dev

 or

 python ./path/to/check_icons_dev.py

```

to make sure the list of icons specified in the icons.toml file are
present in the resource folder of qt_material_icons module
"""

import toml
from pathlib import Path
import shutil

# if we have a qt_material_icons we want to remove it before importing qt_material_icons
# because of a conflict. It allows "normal import" as following and enable usage of
# the script with 'python check_icons_dev.py'

resource_folder = Path(__file__).parent
wrong_path = resource_folder / 'qt_material_icons'
shutil.rmtree(wrong_path, ignore_errors=True)

from qt_material_icons import extract

icon_config = toml.load(resource_folder.joinpath('icons.toml'))

styles = icon_config['icons']['style']
sizes = icon_config['icons']['size']
names = icon_config['icons']['names']

# qtmaterialicons -o 'path/to/resources' --styles outlined rounded  --sizes 40 --names home computer search favorite toggle_off toggle_on

styles = tuple(extract.MaterialIcon.Style(s) for s in styles)

extract.extract_package(output=str(resource_folder))
extract.extract_icons_multi(
    names=names,
    styles=styles,
    sizes=sizes,
    output=str(resource_folder),
)


# After generation, if nothing failed, the old 'material_icons' folder is deleted
# and the 'qt_material_icons' folder generated by 'qt_material_icons' package is
# moved to 'material_icons'
good_path = resource_folder / 'material_icons'
shutil.rmtree(good_path, ignore_errors=True)

wrong_path.rename(good_path)