# This file is specifying the icons names, style, size and filling state necessary for pymodaq
# Their existence will be check by developpers using the check_icons_dev.py script that will add them if necessary
#
# So if a dev need to add a given Material icon (https://fonts.google.com/icons) in a given style, size...
# it should add it here and run the check_icons_dev.py script


[icons]
size = [20, 40]  # add other cases if needed among [20, 24, 40, 48]
style = ['rounded']  # add other cases if needed among ['rounded', 'outlined', 'sharp']
names = [
    'account_tree',
    'add',
    'add_circle',
    'arrows_input',
    'background_replace',
    'bid_landscape',
    'bid_landscape_disabled',
    'blur_circular',
    'blur_linear',
    'blur_off',
    'blur_on',
    'brightness_3',
    'build_circle',
    'cable',
    'camera',
    'close',
    'compare_arrows',
    'deblur',
    'discover_tune',
    'do_not_disturb_on',
    'dock_to_bottom',
    'dock_to_left',
    'extension',
    'file_copy',
    'folder_data',
    'function',
    'gesture',
    'grid_off',
    'grid_on',
    'help',
    'home',
    'info',
    'ink_eraser',
    'ink_eraser_off',
    'input',
    'lightbulb',
    'lock',
    'lock_open_right',
    'looks_one',
    'more_time',
    'motion_play',
    'moving',
    'not_started',
    'pause_circle',
    'plug_connect',
    'refresh',
    'remove',
    'repeat',
    'repeat_on',
    'repeat_one',
    'repeat_one_on',
    'save',
    'save_as',
    'save_clock',
    'search',
    'settings',
    'start',
    'step',
    'step_into',
    'step_out',
    'stop',
    'stop_circle',
    'sync_disabled',
    'sync_lock',
    'target',
    'texture_minus',
    'timer',
    'timer_off',
    'toggle_off',
    'toggle_on',
    'tune',
    'videocam',
    'videocam_off',
    'visibility',
    'visibility_off'
]


