#this is the configuration file of the pymodaq_data package

[data_saving]
    swmr_enabled = false
    swmr_flush_interval = 1

    [data_saving.h5file]
    save_path = "C:\\Data"  #base path where data are automatically saved
    compression_level = 5  # for hdf5 files between 0(min) and 9 (max)

    [data_saving.hsds] #hsds connection option (https://www.hdfgroup.org/solutions/highly-scalable-data-service-hsds/)
    #to save data in pymodaq using hpyd backend towards distant server or cloud (mimicking hdf5 files)
    root_url = "http://hsds.sebastienweber.fr"
    username = "pymodaq_user"
    pwd = "pymodaq"

    [data_saving.data_type]
    # choose from below. This will force the datatype to be saved to
    dynamic =  [ 'float64', 'uint8', 'int8', 'uint16', 'int16', 'uint32', 'int32', 'uint64', 'int64',]

[general]
hdf5_backend = ['tables', 'h5py', 'h5pyd']  # first element is the default, mostly tested with tables

[plotting]
backend = ['matplotlib']  # either 'matplotlib' or 'qt' or any other custom backend
plot_colors = [[255, 255, 255], [255, 0, 0], [0, 255, 0], [0, 0, 255], [14, 207, 189], [207, 14, 166], [207, 204, 14]]
process_roi = true  # if True subdata is extracted from the ROI in the data viewers

