#this is the configuration file of PyMoDAQ Utils


[general]
debug_level = ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]
check_version = false  # automatically check version at startup (or not if False)
message_status_persistence = 1000  # ms

[user]
name = "User name"  # default name used as author in the hdf5 saving files


[network]
    [network.logging]
        [network.logging.user]
        username = "pymodaq_user"
        pwd = "pymodaq"

        [network.logging.sql] #location of the postgresql database server and options where the DAQ_Logger will log data
        ip = "10.47.3.22"
        port = 5432

    [network.tcp-server]
    ip = "10.47.0.39"
    port = 6341

    [network.leco-server]
    run_coordinator_at_startup = false
    host = "localhost"
    port = 12300  # pyleco default Coordinator port
    heartbeat-timeout = 1000  # int, in milliseconds

[backup]
keep_backup = true
folder = "environments"
limit = 25