# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
          
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch hatchling
    - name: Build and publish
      env:
        HATCH_INDEX_USER: ${{ secrets.PYPI_USERNAME }}
        HATCH_INDEX_AUTH: ${{ secrets.PYPI_PASSWORD }}
      run: |
        git fetch --unshallow --tags #Should be taken care of by checkout action with fetch-depth: 0
        last_tag=$(git tag --sort=-creatordate | head -n 1) 
        for package in pymodaq_utils pymodaq_data pymodaq_gui pymodaq; do
          cd packages/${package}
          current_version=$(hatch version)
          if [[ "${current_version}" == "${last_tag}" ]]; then
            hatch build && hatch publish || true # Continue even if one build/publish fails
          fi;
          cd ../../
        done