name: Test for pymodaq_gui

on:
  workflow_dispatch:
  workflow_call:

  pull_request:
    paths:
      - 'packages/pymodaq_gui/**'
    branches:
      - '*'
      - '!badges'
  push:
    paths:
      - 'packages/pymodaq_gui/**'
    branches:
      - '*'
      - '!badges'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-latest"
            python-version: "3.11"
            qt-backend: "pyqt6"
    runs-on: ${{ matrix.os }}
    env:
      PYTEST_QT_API: ${{ matrix.qt-backend }}
      QT_API: ${{ matrix.qt-backend }}    # ensure qtpy picks the backend before any imports
    defaults:
      run:
        working-directory: packages/pymodaq_gui

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> "${GITHUB_OUTPUT}"
        id: extract_branch

      - name: Create badge destination directory
        run: |
          mkdir -p "${{ github.workspace }}/${{ steps.extract_branch.outputs.branch }}"
          echo  ${{ github.workspace }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd ../../
          python install-packages.py -d -u pymodaq_gui

      - name: Install WebEngine
        continue-on-error: true
        run: |
          pip install ${{ 
            matrix.qt-back
